name: Publish journal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 14 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: als-env
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        python -m playwright install-deps
        playwright install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Publish
      run: |
         python scrape.py
         sqlite-utils insert-files foo.db foo 2022/* --text --replace # N.B. change replace to upsert to only insert new records instead
         # cat 2022/* > combined.txt
         git config user.name "Automated"
         git config user.email "actions@users.noreply.github.com"
         git add -A
         git commit -m 'adding all new files'
         git push
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@v0
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region asia-southeast1
        gcloud config set project daily-al-run
        datasette publish cloudrun foo.db --service=daily-al-run --metadata metadata.json
        
