name: Publish journal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        python -m playwright install-deps
        playwright install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Publish
      run: |
         python scrape.py
         git config user.name "Automated"
         git config user.email "actions@users.noreply.github.com"
         git add foo.txt
         git commit -m 'adding foo.txt'
         git push
